# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{term-extraction}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["alex"]
  s.date = %q{2011-10-27}
  s.description = %q{Term extraction library}
  s.email = %q{alexrabarts@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION.yml",
    "lib/term_extraction.rb",
    "lib/term_extraction/yahoo.rb",
    "lib/term_extraction/zemanta.rb",
    "term-extraction.gemspec",
    "test/fixtures/yahoo.xml",
    "test/fixtures/yahoo2.xml",
    "test/fixtures/zemanta.xml",
    "test/fixtures/zemanta2.xml",
    "test/term_extraction_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/alexrabarts/term_extraction}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Provides access to term extraction APIs such as Yahoo! Term Extraction API and Zemanta.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<rdoc>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.0.7"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 1.0.7"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 1.0.7"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

